refactor(table): change table component to use generics
HospitalRun/components pull request #562
Opened 2020-08-22 21:23 UTC by rsousaj

Fixes #549 .

**Changes proposed in this pull request:**
- Table components now using Generics

2020-08-29 15:37 UTC, jackcmeyer commented
change looks good to me. Just waiting on @rsousaj to sign the CLA.

2020-08-29 17:07 UTC, rsousaj commented
Sorry about that, I forgot that frontend and components are different projects.

But now that I've already signed it, it still look pending. Am I messing around ?

2020-09-02 14:38 UTC, fox1t requested changes

2020-09-02 14:38 UTC, fox1t commented on src/components/Table/Table.tsx
> +  [key: string]: any
```suggestion
  [key: string]: unknown
```

2020-09-03 18:38 UTC, hugo1707 commented
Hello, 
I suggest changing it to ReactNode to fix these errors

2020-09-14 15:23 UTC, morrme commented
@hugo1707 @rsousaj  What is the status of this PR?

2020-09-14 19:49 UTC, rsousaj commented
> @hugo1707 @rsousaj What is the status of this PR?

Hi @morrme, what do you think about @hugo1707 question ? Should we change it to ReactNode instead of 'unknown' ?

2020-10-08 17:01 UTC, blestab submitted a review, later dismissed

2020-10-08 20:17 UTC, tehKapa commented
> > @hugo1707 @rsousaj What is the status of this PR?
> 
> Hi @morrme, what do you think about @hugo1707 question ? Should we change it to ReactNode instead of 'unknown' ?

@rsousaj try it. in case it should continue to give error

2020-10-15 18:13 UTC, rsousaj commented
> > > @hugo1707 @rsousaj What is the status of this PR?
> > 
> > 
> > Hi @morrme, what do you think about @hugo1707 question ? Should we change it to ReactNode instead of 'unknown' ?
> 
> @rsousaj try it. in case it should continue to give error

Hi guys, sorry for taking too long to reply. I didn't have internet last couple of days. We'll try that.

2020-10-18 15:10 UTC, tehKapa approved these changes

2020-10-18 15:11 UTC, merged