Update sb
HospitalRun/components pull request #637
Opened 2020-10-28 22:50 UTC by RobertoMSousa

Fixes callout, breadcrumbs and calendar stories.

**Changes proposed in this pull request:**
Update the docs of the components mentioned previously to allow the storybook 6 to render the docs page and fix a bug on the calendar that was preventing the component to be rendered at all on storybook.

*Note: pull requests without proper descriptions may simply be closed without further discussion. We appreciate your contributions, but need to know what you are offering in clearly described format. Provide tests for all code that you add/modify. If you add/modify any components update the storybook. Thanks! (you can delete this text)*

2020-10-29 00:05 UTC, jackcmeyer requested changes

2020-10-29 00:05 UTC, jackcmeyer commented on stories/callout.stories.tsx
> +// import { storiesOf } from '@storybook/react'
commented out import

2020-10-29 00:05 UTC, jackcmeyer commented on stories/calendar.stories.tsx
> +// main story tha's editable and has the docs for the props
small spelling typo

2020-11-01 15:34 UTC, blestab approved these changes
LGTM except for the typo mentioned by @jackcmeyer

2020-11-01 15:35 UTC, blestab requested changes
LGTM except for the typo mentioned by @jackcmeyer

2020-11-06 21:43 UTC, RobertoMSousa commented
@blestab , typo fixed.
thanks 🙂

2020-11-07 19:22 UTC, blestab commented
Thanks @RobertoMSousa 
May you address the commented out import in `stories/callout.stories.tsx` as per @jackcmeyer comment i.e. if we are no longer using it then let's remove it.

2020-11-08 00:53 UTC, RobertoMSousa commented
> Thanks @RobertoMSousa
> May you address the commented out import in `stories/callout.stories.tsx` as per @jackcmeyer comment i.e. if we are no longer using it then let's remove it.

That was already removed on t[his commit ](https://github.com/HospitalRun/components/pull/637/commits/b5f80ad7ccd9aa77f36dd1b5b6522a9853032e5c)

2020-11-08 13:19 UTC, tehKapa approved these changes

2020-11-08 13:19 UTC, merged